### PR TITLE
Fix resize handle

### LINKED ISSUE #141: Fix right sidebar dragging
The right sidebar where the file details are displayed is intended to be draggable for expanding or minimizing the sidebar width, however at the moment it doesn't seem to actually move anything other than the contents.

### PR DESCRIPTION
**Pull request by SeanLeRoy**
The resize handle was broken because the width of the rest of the app was set to a fixed `80%` which meant that it wasn't considering the adjustment from the variable `--file-details-width` which is what determines the right sidebar pane's width. After changing the width calcuation this worked, added some styling changes to make it not have strange horizontal scroll behavior.

Resolves #141

### CODE REVIEW

File: packages/core/components/FileDetails/index.tsx [hunk 1]
```diff
@@ -99,57 +99,55 @@ export default function FileDetails(props: Props) {
             className={classNames(styles.root, styles.expandableTransition, props.className)}
             id={FILE_DETAILS_PANE_ID}
         >
-            <div className={styles.fileDetailsContent}>
```
Comment (SeanLeRoy) [inline packages/core/components/FileDetails/index.tsx:102]: Only change here is I deleted the `<div className={styles.fileDetailsContent}>` element which changed the indentation

**Review by aswallace — APPROVED** [review]

File: packages/core/components/FileDetails/index.tsx [hunk 2]
```diff
@@ -99,57 +99,55 @@ export default function FileDetails(props: Props) {
...
-                                <h4>Information</h4>
-                                <FileAnnotationList
-                                    className={styles.annotationList}
-                                    fileDetails={fileDetails}
-                                    isLoading={isLoading}
+            <div
+                className={styles.resizeHandle}
+                onMouseDown={(e) => resizeHandleOnMouseDown(e)}
+                // TODO:???
+                onDoubleClick={resizeHandleDoubleClick}
```
Comment (aswallace) [inline packages/core/components/FileDetails/index.tsx:106]: unrelated to PR, I'm curious what this to do is/what the behavior will be

**Review by BrianWhitneyAI — APPROVED** [review]

File: packages/core/components/FileDetails/index.tsx (hunk 2 above)
Comment (SeanLeRoy) [reply packages/core/components/FileDetails/index.tsx:106]: Ah I can remove that `TODO` this actually just resets the width of the pane back to `20%` from whatever it was
